# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ------------- Tests ----------------

      - name: test demux8way
        run: |
          pytest hw/test_components.py -k test_deMux8way

      - name: test deMux4way
        run: |
          pytest -k deMux4way 

      - name: test barrelShifter
        run: |
          pytest -k barrelShifter

      - name: test orNway
        run: |
          pytest hw/test_components.py -k orNway 

      - name: test mux4way
        run: |
          pytest -k test_mux4way -v

      - name: test Or8way
        run: |
          pytest -k test_or8way 
